# Generated by Django 4.2.3 on 2023-08-13 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_program_registered_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='registered_users',
            field=models.ManyToManyField(blank=True, related_name='registered_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
