# Generated by Django 4.2.3 on 2023-08-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1', models.FileField(blank=True, null=True, upload_to='', verbose_name='가족관계증명서')),
                ('file2', models.FileField(blank=True, null=True, upload_to='', verbose_name='주민등록등본')),
                ('file3', models.FileField(blank=True, null=True, upload_to='', verbose_name='장애인등록증')),
                ('file4', models.FileField(blank=True, null=True, upload_to='', verbose_name='정부기관심사결과지')),
            ],
        ),
    ]
