# Generated by Django 4.2.4 on 2023-08-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='applicant',
            field=models.IntegerField(default=15, verbose_name='마감 인원'),
        ),
    ]
